// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheKittySaver.AdoptionSystem.Persistence.DbContexts.WriteDbContexts;

#nullable disable

namespace TheKittySaver.AdoptionSystem.Persistence.Migrations
{
    [DbContext(typeof(ApplicationWriteDbContext))]
    [Migration("20251226232943_IntroducingArchievedAt")]
    partial class IntroducingArchievedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.Address#AdoptionAnnouncementAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CountryCode")
                                .HasColumnType("int")
                                .HasColumnName("AddressCountryCode");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "City", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.Address#AdoptionAnnouncementAddress.City#AddressCity", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("AddressCity");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Line", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.Address#AdoptionAnnouncementAddress.Line#AddressLine", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("AddressLine");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "PostalCode", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.Address#AdoptionAnnouncementAddress.PostalCode#AddressPostalCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("AddressPostalCode");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Region", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.Address#AdoptionAnnouncementAddress.Region#AddressRegion", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("AddressRegion");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ArchivedAt", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.ArchivedAt#ArchivedAt", b1 =>
                        {
                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ArchivedAt");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ClaimedAt", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.ClaimedAt#ClaimedAt", b1 =>
                        {
                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ClaimedAt");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Description", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.Description#AdoptionAnnouncementDescription", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("Description");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PhoneNumber");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_mergeLogs", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement._mergeLogs#AdoptionAnnouncementMergeLog", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("MergedAdoptionAnnouncementId");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "MergedAt", "TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement._mergeLogs#AdoptionAnnouncementMergeLog.MergedAt#AdoptionAnnouncementMergetAt", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateTimeOffset>("Value")
                                        .HasJsonPropertyName("MergedAt");
                                });

                            b1.ToJson("_mergeLogs");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("AdoptionAnnouncements", (string)null);
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdoptionAnnouncementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AdoptionHistory", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.AdoptionHistory#AdoptionHistory", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("LastReturnDate")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("AdoptionHistoryLastReturnDate");

                            b1.Property<string>("LastReturnReason")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("AdoptionHistoryLastReturnReason");

                            b1.Property<int>("ReturnCount")
                                .HasColumnType("int")
                                .HasColumnName("AdoptionHistoryReturnCount");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Age", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.Age#CatAge", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Age");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ArchivedAt", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.ArchivedAt#ArchivedAt", b1 =>
                        {
                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ArchivedAt");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ClaimedAt", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.ClaimedAt#ClaimedAt", b1 =>
                        {
                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ClaimedAt");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Color", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.Color#CatColor", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Color");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Description", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.Description#CatDescription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("Description");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Gender", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.Gender#CatGender", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Gender");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "HealthStatus", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.HealthStatus#HealthStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("HealthStatus");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "InfectiousDiseaseStatus", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.InfectiousDiseaseStatus#InfectiousDiseaseStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FelvStatus")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("InfectiousDiseaseStatusFelvStatus");

                            b1.Property<string>("FivStatus")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("InfectiousDiseaseStatusFivStatus");

                            b1.Property<DateOnly>("LastTestedAt")
                                .HasColumnType("date")
                                .HasColumnName("InfectiousDiseaseStatusLastTestedAt");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ListingSource", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.ListingSource#ListingSource", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ListingSourceSourceName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ListingSourceType");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.Name#CatName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NeuteringStatus", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.NeuteringStatus#NeuteringStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsNeutered")
                                .HasColumnType("bit")
                                .HasColumnName("NeuteringStatusIsNeutered");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PublishedAt", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.PublishedAt#PublishedAt", b1 =>
                        {
                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("PublishedAt");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SpecialNeeds", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.SpecialNeeds#SpecialNeedsStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("SpecialNeedsStatusDescription");

                            b1.Property<bool>("HasSpecialNeeds")
                                .HasColumnType("bit")
                                .HasColumnName("SpecialNeedsStatusHasSpecialNeeds");

                            b1.Property<string>("SeverityType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SpecialNeedsStatusSeverityType");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Temperament", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.Temperament#Temperament", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Temperament");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Weight", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat.Weight#CatWeight", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("ValueInKilograms")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("WeightValueInKilograms");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AdoptionAnnouncementId");

                    b.HasIndex("PersonId");

                    b.ToTable("Cats", (string)null);
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.CatGalleryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DisplayOrder", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.CatGalleryItem.DisplayOrder#CatGalleryItemDisplayOrder", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("DisplayOrder");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("CatGalleryItems", (string)null);
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.CatThumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CatId")
                        .IsUnique();

                    b.ToTable("CatThumbnails", (string)null);
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Vaccination", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Date", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Vaccination.Date#VaccinationDate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("VaccinationDate");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "VeterinarianNote", "TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Vaccination.VeterinarianNote#VaccinationNote", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("VeterinarianNote");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Vaccinations", (string)null);
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountryCode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "City", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Address.City#AddressCity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Line", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Address.Line#AddressLine", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Line");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Address.Name#AddressName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PostalCode", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Address.PostalCode#AddressPostalCode", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PostalCode");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Region", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Address.Region#AddressRegion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Region");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ArchivedAt", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person.ArchivedAt#ArchivedAt", b1 =>
                        {
                            b1.Property<DateTimeOffset>("Value")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("ArchivedAt");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PhoneNumber", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PhoneNumber");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Username", "TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person.Username#Username", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Username");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement", b =>
                {
                    b.HasOne("TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat", b =>
                {
                    b.HasOne("TheKittySaver.AdoptionSystem.Domain.Aggregates.AdoptionAnnouncementAggregate.Entities.AdoptionAnnouncement", null)
                        .WithMany()
                        .HasForeignKey("AdoptionAnnouncementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.CatGalleryItem", b =>
                {
                    b.HasOne("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat", null)
                        .WithMany("GalleryItems")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.CatThumbnail", b =>
                {
                    b.HasOne("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat", null)
                        .WithOne("Thumbnail")
                        .HasForeignKey("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.CatThumbnail", "CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Vaccination", b =>
                {
                    b.HasOne("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat", null)
                        .WithMany("Vaccinations")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Address", b =>
                {
                    b.HasOne("TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person", null)
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.CatAggregate.Entities.Cat", b =>
                {
                    b.Navigation("GalleryItems");

                    b.Navigation("Thumbnail");

                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("TheKittySaver.AdoptionSystem.Domain.Aggregates.PersonAggregate.Entities.Person", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
